### ISSUE TITLE
HACS support

### ISSUE THREAD

**Issue by LbDab** [postlund/search-card#1]
Feature request: Add HACS support:

https://custom-components.github.io/hacs/developer/general/

Great and useful card thanks

**Comment by postlund** [comment]
Yes, that is a good request. I added a sample info.md to show some information, so it should work. Could you manually try adding it to your installation (under `Settings`) and see if it works? If I get an OK, I will push it to the default repo.

**Comment by LbDab** [comment]
Yes it works:

![search](https://user-images.githubusercontent.com/47884140/62238672-236c7c00-b3dc-11e9-9fe4-c8f1a5721400.JPG)

**Comment by postlund** [comment]
Great, thanks! I'll make sure it ends up in the default repo.

**Comment by postlund** [comment]
Pull request created here: custom-components/hacs#372.

**Comment by ludeeus** [comment]
Merged 👍

**Comment by postlund** [comment]
Great, Thanks! 👍
