### ISSUE TITLE
Can't install ('LitElement' not found)

### ISSUE THREAD

**Issue by Vedeneb** [postlund/search-card#10]
Hi, thanks for the great card, however I can't use it. I'm running Hass 0.99.2 and I'm getting this Error:
![image](https://user-images.githubusercontent.com/39202639/66274902-a51cd200-e883-11e9-8b51-58202ffaac6e.png)

However the card is installed. In the Chrome Dev Tools I found the following:
![image](https://user-images.githubusercontent.com/39202639/66274917-c7aeeb00-e883-11e9-8b95-51cec41762ba.png)

Looks like it can't find the 'LitElement' dependency:
![image](https://user-images.githubusercontent.com/39202639/66274930-e0b79c00-e883-11e9-9f54-b93883cbfce2.png)

Do I have to install something to get it work?

Let me know if you need further information.

Thanks!

**Comment by postlund** [comment]
You need cardtools as well, did you install that?

**Comment by Vedeneb** [comment]
Yes it is installed:
![image](https://user-images.githubusercontent.com/39202639/66312776-8b29d080-e911-11e9-9032-f056e19b5876.png)

**Comment by postlund** [comment]
I believe you have a very old version of cardtools, try upgrading to latest version and see if it helps.

**Comment by Vedeneb** [comment]
Yep. That was the mistake. Working fine now, thanks! Would you mind adding a note to the FAQ's or somewhere that card-tools must be installed and up to date? Thanks.

**Comment by postlund** [comment]
Sorry for not answering! I will try to make a note about that, absolutely!
