### ISSUE TITLE
Search Box Input Type

### ISSUE THREAD

**Issue by dannyhanes** [postlund/search-card#12]
I am not sure if this is a "search-card" issue, or a 1Password issue, but if it's not already, can the input type be changed to something that password managers would ignore? Right now on my phone (Pixel 3 XL) when I go to type into the box, 1Password will pop up and offer suggestions. I believe if the type is set to "search" then this _shouldn't_ happen. 

I am looking to see if there is a way to block the pop up from 1Password, but so far I have had no luck. 

Thanks!

**Comment by postlund** [comment]
I'm not sure how password managers detect which boxes to auto fill, but I assume it is possible to fix somehow. I will have a look at it when I have some time.
