### ISSUE TITLE
Lovelace card config updating itself

### ISSUE THREAD

**Issue by gitrummy** [postlund/search-card#16]
I have an issue where the card configuration keeps updating itself as below.
Any ideas why it might be doing this? Many thanks.

max_results: 10
type: 'custom:search-card'
actions:
  - &ref_0
    matches: '^((magnet:.*)|(.*.torrent.*))$'
    name: Add to Transmission
    icon: 'mdi:progress-download'
    service: transmission.add_torrent
    service_data:
      torrent: '{1}'
  - *ref_0
  - *ref_0
  - *ref_0
  - matches: '^((magnet:.*)|(.*.torrent.*))$'
    name: Add to Transmission
    icon: 'mdi:progress-download'
    service: transmission.add_torrent
    service_data:
      torrent: '{1}'
  - matches: '^((magnet:.*)|(.*.torrent.*))$'
    name: Add to Transmission
    icon: 'mdi:progress-download'
    service: transmission.add_torrent
    service_data:
      torrent: '{1}'
  - matches: '^((magnet:.*)|(.*.torrent.*))$'
    name: Add to Transmission
    icon: 'mdi:progress-download'
    service: transmission.add_torrent
    service_data:
      torrent: '{1}'
  - matches: '^((magnet:.*)|(.*.torrent.*))$'
    name: Add to Transmission
    icon: 'mdi:progress-download'
    service: transmission.add_torrent
    service_data:
      torrent: '{1}'
  - matches: '^((magnet:.*)|(.*.torrent.*))$'
    name: Add to Transmission
    icon: 'mdi:progress-download'
    service: transmission.add_torrent
    service_data:
      torrent: '{1}'
  - matches: '^((magnet:.*)|(.*.torrent.*))$'
    name: Add to Transmission
    icon: 'mdi:progress-download'
    service: transmission.add_torrent
    service_data:
      torrent: '{1}'
  - matches: '^((magnet:.*)|(.*.torrent.*))$'
    name: Add to Transmission
    icon: 'mdi:progress-download'
    service: transmission.add_torrent
    service_data:
      torrent: '{1}'
  - matches: '^((magnet:.*)|(.*.torrent.*))$'
    name: Add to Transmission
    icon: 'mdi:progress-download'
    service: transmission.add_torrent
    service_data:
      torrent: '{1}'
  - matches: '^((magnet:.*)|(.*.torrent.*))$'
    name: Add to Transmission
    icon: 'mdi:progress-download'
    service: transmission.add_torrent
    service_data:
      torrent: '{1}'

**Comment by cherokee93** [comment]
+1

Also, the add torrent function would really interesting and appreciated, but it doesn't work in my setup. It needs the **name:** of transmission instance configured via Integrations via service_data.

**Comment by derandiunddasbo** [comment]
It'a a bit confusing, that this issue has been closed by the opener without being solved and without any comment on why he closed it.

However, if someone stumbles upon this ticket and is wondering, if this issue is still being worked on, there is indeed another (still open) ticket regarding the same bug: https://github.com/postlund/search-card/issues/11

**Comment by cherokee93** [comment]
Yeah, I have no idea why @gitrummy closed this.
 Let's continue in the other issue, maybe I should try to edit [this](https://github.com/postlund/search-card/issues/11#issuecomment-585077302)

**Comment by gitrummy** [comment]
My bad.

**Comment by gitrummy** [comment]
Solved in latest Core updates.
