### ISSUE TITLE
Requires card_tools, but this is not added by HACS

### ISSUE THREAD

**Issue by DrJohnT** [postlund/search-card#18]
I added your card using HACS and added following to my Lovelace UI

```yaml
type: 'custom:search-card'
max_results: 10
```
but then I got the error
```
Can't find card_tools. See https://github.com/thomasloven/lovelace-card-tools
```

Of course, I added the card-tools module manually to my config. 

But why is card_tools not added by installation of your plug-in??

**Comment by postlund** [comment]
AFAIK, HACS does not support dependencies.
