### ISSUE TITLE
search field loosing focus

### ISSUE THREAD

**Issue by tht** [postlund/search-card#20]
I absolutely love the idea behind the search-card, so I included it in my Home-Assistant 0.108 installation. I moved to 0.109.2 today and see the same issue. Tested using search-card `4bc0ab8 `.

When I open the Lovelace UI there is the input field waiting. I click in it to set the keyboard focus and start typing. When entering the first letter it shows up in the textfield and the found entries appear below for a fraction of a second. Then the keyboard focus is lost again and the input field empty. I have to click a second time in the input field - this time it works as expected.

Testes using Safari on macOS and also the Chromium based Brave browser. Also tested in the iOS companion app. All three behave the same. I've put the search-card on an empty view, same issue there. So I assume no conflict with another card.

This is how the search-card is configured:
```
      - type: custom:search-card
        max_results: 10
```

Do others experience the same issue? Or is it a conflict with another plugin I installed?

Thanks for looking into this.

**Comment by migo-dev** [comment]
Same happening here since a few weeks (or months?) (0.109.2 - Chrome, Android & iOS App)

I haven't seen any complaints online, so I assumed to have made a mistake or as you suggested a conflicting plugin.

**Comment by tht** [comment]
Thanks for your feedback. Good to know I'm not the only one.

If you are interested, here the list of all my plugins. "Custom Header" could be an issue, the others are most likely ok.

![image](https://user-images.githubusercontent.com/2557225/80818628-d8360280-8bd3-11ea-9c74-d25d8e780815.png)

**Comment by postlund** [comment]
I see this issue as well, but I'm not really sure why the problem is (javascript is not really my strongest suit). So if anyone has an idea, feel free me to send a PR to fix it.

**Comment by migo-dev** [comment]
Hey guys,
I installed 0.110.1 today and think this bug seems to be gone? I tested at least 5 times (force close app & searched right after opening) with success 👍

**Comment by postlund** [comment]
Yeah, seems to work fine for me as well! 👍

**Comment by tht** [comment]
Same here… 0.110.1 seems to have fixed it.
But it broke Compact Headers for me – a different story :).

**Comment by migo-dev** [comment]
@tht `conversation:` in configuration.yaml fixed the header for me :)

**Comment by rjmcfadd** [comment]
Since the last home assistant update (2024.07) this search field loses focus after typing in the first letter.

**Comment by JBS5** [comment]
> Since the last home assistant update (2024.07) this search field loses focus after typing in the first letter.

Did you already updated HA and saw this issue is fixed?

**Comment by JBS5** [comment]
Still relevant. After seeing [this change](https://github.com/postlund/search-card/commit/638f0b48945316846e26f10f1e3024d816639051), I was hoping this issue is fixed, but unfortunally it's not.

**Comment by rjmcfadd** [comment]
> Still relevant. After seeing [this change](https://github.com/postlund/search-card/commit/638f0b48945316846e26f10f1e3024d816639051), I was hoping this issue is fixed, but unfortunally it's not.

It is fixed for me now!

**Comment by JBS5** [comment]
> > Still relevant. After seeing [this change](https://github.com/postlund/search-card/commit/638f0b48945316846e26f10f1e3024d816639051), I was hoping this issue is fixed, but unfortunally it's not.
> 
> It is fixed for me now!

For me the focus is still lost after the initial search after opening the app. After clearing the search input and re-entering some chars, it keeps it focus. But, every first search, it's lost after entering 1 or 2 chars.

Happens both on mobile using the HA app as on desktop, 

\\Edit: It looks like it has something to do with other components on that page. When I use the search-card on another blank tab, I don't experience the issue.
