### ISSUE TITLE
No icon as of 0.110

### ISSUE THREAD

**Issue by migo-dev** [postlund/search-card#21]
Nothing dramatic - just wanted to let you know the icons don't show as of HA 0.110. Probably related to this https://www.home-assistant.io/blog/2020/05/20/release-110/#icons

**Comment by postlund** [comment]
Yeah, seems to be the case. Will have to look into that in due time.

**Comment by migo-dev** [comment]
No hurry - doesn't bother me at all

**Comment by samrenfrew** [comment]
@migo-dev @postlund I managed to fix this locally by replacing 'iron-icon' with 'ha-icon' and changing the 'paper-icon-button' to a standard 'paper-button' and putting the ha-icon inside the element

**Comment by KTibow** [comment]
@migo-dev mind closing this (I forgot to mention before it was merged, so not auto-closed)?

**Comment by postlund** [comment]
I think "Fixes #..." must be part of the commit message or PR body for that to work. So that's probably why it didn't work.

**Comment by migo-dev** [comment]
Hey guys, thank you very much. Great improvement! Also thanks for the custom placeholder text 😄 
I found a way to get the old close icon back:

[Lines 61-65]
>             <ha-icon-button slot="suffix"
>                               @click="${this._clearInput}"
>                               icon="mdi:close"
>                               alt="Clear"
>                               title="Clear"></ha-icon-button>

**Comment by KTibow** [comment]
> which part is "responsible" for the small extra x?
That's the built-in browser behavior.

**Comment by KTibow** [comment]
https://stackoverflow.com/questions/14007655/remove-ie10s-clear-field-x-button-on-certain-inputs
https://geektnt.com/how-to-remove-x-from-search-input-field-on-chrome-and-ie.html

**Comment by migo-dev** [comment]
Thanks, I see.. is there a way to hide it?

**Comment by KTibow** [comment]
@migo-dev ???
